"""Mudanca em availability

Revision ID: 21d2fe7ca352
Revises: 558af2ded790
Create Date: 2024-05-14 12:15:29.686454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d2fe7ca352'
down_revision: Union[str, None] = '558af2ded790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'costumes',
		sa.Column(
			'availability',
			sa.Enum('AVAILABLE', 'UNAVAILABLE', name='costumeavailability'),
			nullable=False,
		),
	)
	op.drop_column('costumes', 'available')
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'costumes', sa.Column('available', sa.BOOLEAN(), nullable=False)
	)
	op.drop_column('costumes', 'availability')
	# ### end Alembic commands ###
